### ISSUE TITLE
implement sessions

### ISSUE THREAD

**Issue by chefjuanpi** [CocoaWebStudio/apollo-server-boilerplate#13]
Sessions is a very important part on any API,

**Comment by PranjalAgni** [comment]
Can you please elaborate for what purpose we need to implement sessions

**Comment by chefjuanpi** [comment]
for security and facilitate sessions.

This moment I implement JWT. The user connect to the API by the mutation SignIn using their email and password.
If authorization is valid the server will create, sign and send on header.authenticate the JWT it contains info about the user and the key used to sign the JWT.

After that on a next call on context function is possible to validate the JWT, the user can send it by the header authenticate and use the info on it to track the connected user on the DB. after that we can set the connected user on the apollo-server context and use it for authorize or deny permissions.

This approach is not good for scalability, the multiple db call can slow the system creating a bottle neck. we can set the user info we will need on the JWT, like email, roles. this approach is not full safety because the JWT body can be readed easily.

A better solution is use a session layer with Redis, memcached or similar that runs faster than the DB and keep all the data on the serverside.

**The plan (using redis as example) :**
- Sing In: after validate the user credentials create a session on redis containing the user data.
- sent to the user a session cookie or a JWT containing the session id only.
- On context validate the authenticate header, and use the session:id to recovery the user info and set this on the context.
- Use the connected user info for validate permissions at resolver or schema level.
