### ISSUE TITLE
Start Testing 

### ISSUE THREAD

**Issue by chefjuanpi** [CocoaWebStudio/apollo-server-boilerplate#6]
It need test, the test need to be simple and a good example as starting point when someone use this boilerplate for their owns projects.

**Comment by carlospatinos** [comment]
Can i take this? If so can you assign this to me pls

**Comment by chefjuanpi** [comment]
sure

**Comment by chefjuanpi** [comment]
@carlospatinos  I write an smal e2e test and install jest all necessary packages for start the test. I close this issue for now, but the repo requires more test. 

Your help is always welcome !
